"""add_encrypted_fields

Revision ID: cfb81dc8d7eb
Revises: 688fa8e2ec45
Create Date: 2026-05-08 21:15:32.278624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb81dc8d7eb'
down_revision: Union[str, Sequence[str], None] = '688fa8e2ec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_email', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('encrypted_phone', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'encrypted_phone')
    op.drop_column('users', 'encrypted_email')
    # ### end Alembic commands ###
